"""init db

Revision ID: 7e84dd0123f1
Revises: 
Create Date: 2026-07-07 14:58:16.932875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e84dd0123f1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('users',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('team_name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['team_name'], ['teams.name'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('pull_requests',
    sa.Column('pull_request_id', sa.String(), nullable=False),
    sa.Column('pull_request_name', sa.String(), nullable=False),
    sa.Column('author_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'MERGED', name='pullrequeststatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('merged_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('pull_request_id')
    )
    op.create_table('reviewer_assignments',
    sa.Column('pull_request_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.pull_request_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('pull_request_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviewer_assignments')
    op.drop_table('pull_requests')
    op.drop_table('users')
    op.drop_table('teams')
    # ### end Alembic commands ###
